apiVersion: v1
kind: Namespace
metadata:
  name: challenge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idwall
  namespace: challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idwall
  template:
    metadata:
      labels:
        app: idwall
    spec:
      containers:
      - name: idwall
        image: idwall:1.0
        env:
          - name: NAME
            value: Thiago
---
apiVersion: v1
kind: Service
metadata:
  name: idwall
  namespace: challenge
spec:
  type: NodePort
  selector:
    app: idwall
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idwall
  namespace: challenge
spec:
  rules:
  - host: idwall.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: idwall
            port:
              number: 31000

