# DevOps Challenge Idwall .::. Thiago Paz #

replicaCount: 1

image:
  repository: idwall
  pullPolicy: IfNotPresent
  tag: "1.0"

envname: NAME
envvalue: Thiago

namespace: challenge

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

containerPort: 3000

service:
  port: 3000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  spec:
    defaultBackend:
      service:
        name: idwall
        port:
          number: 80
  hosts:
    - host: idwall.cc
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: idwall
              port:
                number: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
